
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Online_Exam_Project_Main.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Candidate_tbl
{

    public Candidate_tbl()
    {

        this.Result_tbl = new HashSet<Result_tbl>();

    }


    public int candidate_id { get; set; }

    public string candidate_name { get; set; }

    public string candidate_password { get; set; }

    public string candidate_email { get; set; }

    public Nullable<decimal> candidate_contact { get; set; }

    public string candidate_institution { get; set; }



    public virtual ICollection<Result_tbl> Result_tbl { get; set; }

}

}
