
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Online_Exam_Project_Main.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Questions_tbl
{

    public int all_qus_id { get; set; }

    public Nullable<int> qus_id { get; set; }

    public Nullable<int> admin_id { get; set; }

    public Nullable<int> exam_id { get; set; }

    public string qus_title { get; set; }

    public string ans1 { get; set; }

    public string ans2 { get; set; }

    public string ans3 { get; set; }

    public string ans4 { get; set; }

    public Nullable<int> correct_ans { get; set; }



    public virtual Admin_tbl Admin_tbl { get; set; }

    public virtual Exam_tbl Exam_tbl { get; set; }
        public int? selectedvalue { get; set; }
    }

}
